before_script:
    - pip install Sphinx

build_job:
    stage: build
    script:
        - cd en
        - make clean
        - make html
    artifacts:
        name: "$CI_BUILD_REF_NAME"
        paths:
        - en/build/html
